import Head from 'next/head'
import Navbar from '../../components/Navbar'
import Hero from '../../components/Hero'

export default function Home() {
  return (
    <>
      <Head>
        <title>Dylan Rambarran</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='h-screen flex flex-col'>
        <Navbar />
        <Hero />
      </main>
    </>
  )
}
